### ISSUE TITLE
Can't use custom curve function

### ISSUE THREAD

**Issue by ethanbond** [Monadical-SAS/redux-time#10]
I'm having a ton of fun with this, thanks folks!

The docs seem to say that you can have a custom curve function, but it doesn't seem like you actually can and the source also seems to imply that you can't.

Should this already be possible? If not, I can give a PR a shot.

**Comment by pirate** [comment]
Glad you're enjoying it so far!

Good catch, it looks like we accidentally removed the ability to use a custom curve function during one of the last refactors!

Just fixed it in f9895c4, v0.0.25.  Let me know if you still have any trouble!
