### ISSUE TITLE
missing elements in animations.queue

### ISSUE THREAD

**Issue by valkheim** [Monadical-SAS/redux-time#16]
Hi,

We're trying to use your library with a sigma.js graph that displays incomming websocket messages. The idea with redux-time is to be able to travel time within this graph.
We're encountering a strange issue with the queue.
We are accumulating nodes/edges each second (each time we receive a message from ws) on animations.state.graph.{nodes|edges}.
Things become more complicated when we try to play with the speed (from pause to other state (eg backward/forward/play) or backward to forward), the queue is missing some elements when we come back at the moment we changed the speed.

Become actions are dispatched for each node/edge. They are enumerated on an array (graph/{nodes|edges}). Here is the console.log of the last record of state.animations.queue :

![2018-03-30_15-04-40](https://user-images.githubusercontent.com/18068904/38138529-bad010ca-342b-11e8-8496-aebdfad077a1.png)

Nodes and edges are properly dispatched (e1 then e2 then e3 and so on...)
In this example, we waited 7 messages at speed 1. Then, we gone backward (speed = -1) and forward (speed = 1). Bug occured when we reached back the point we set speed = -1. It then crashed because sigmajs tried to link unknow elements.

Here is our store initialisation :
```
[imports]

const finalCreateStore = applyMiddleware(discardMiddleware)(createStore)

const reducers = combineReducers({
  time: timeReducers,
  animations: animationsReducer,
})

const store = finalCreateStore(reducers)

const initialState = { messages: [{ text: "No message", style: {} }], graph: { nodes: [], edges: [] } }
startAnimation(store, initialState)

export {store, initialState}
```

Here are our actions :
```
[imports]

const addNodeAction = (data) => {
  return {
    type: 'ANIMATE', animations: [
      Become({
        path: '/graph/nodes',
        state: _.concat(Object.values(store.getState().animations.state.graph.nodes), data),
        start_time: Date.now(),
      }),
    ]
  }
}

const addEdgeAction = (data) => {
    [same structure]
}

export { addNodeAction, addEdgeAction }
```

Do you have any idea why data is missing in animations.queue ?

**Comment by valkheim** [comment]
That may concern @jbguerraz now 🙃

**Comment by pirate** [comment]
@valkheim @jbguerraz do you still want help with this?  Feel free to DM me on twitter @theSquashSH.  One thing to check is that there's a hard-coded limit to how many animations we store backwards and forwards for time travel for performance reasons, right now it's 2000 but you can increase it by setting `animations.max_time_travel = 10000` in the redux store.
