### ISSUE TITLE
"Animate" is undefined?

### ISSUE THREAD

**Issue by ethanbond** [Monadical-SAS/redux-time#8]
Hello – I might be missing something obvious here, but it looks like `Animate` isn't exported from main?

Installed via `yarn add redux-time`, I'm using ES6 with Typescript

```typescript
import { Animate } from "redux-time";

const simpleAnimation = Animate({
  path: "/progress",
  start_state: 0,
  end_state: 100,
  duration: 2000,
});

export const startAnimation = () =>
  (dispatch: Dispatch<IAppState>, getState: () => IAppState) => {
  dispatch({type: 'ANIMATE', animation: simpleAnimation});
};
```

If I `import * as ANIMATE from "redux-time"; console.log(ANIMATE)` first, I see:

![image](https://user-images.githubusercontent.com/3400321/33436089-10bfae56-d5b2-11e7-978d-59c565b4574f.png)

**Comment by MiltonLn** [comment]
Hello @ethanbond, can you try importing `Animate` from `/node/animations`?

```javascript
import { Animate } from 'redux-time/node/animations'
``` 
Have a nice day!

**Comment by ethanbond** [comment]
Thanks @MiltonLn that seems to have worked! Also had to add `babel-runtime` to my repo, and also not kick off the `Animate({})` call where I did...

Thank you for the help, excited to play around with this.

**Comment by pirate** [comment]
Fixed the docs here: https://github.com/Monadical-SAS/redux-time/commit/70a1327f943c439ef2d4db416706e45bfb4d0cf0

Keep in mind that calling `Animate` does not kick off the animation, it merely creates the animation object.  To actually start the animation you have to dispatch it to the redux store `{type: ANIMATE, ...}` where you ran `startAnimation`.
